survey.Kameda.raw0<-
  read.csv(
    file=paste(
      data.loc(),
      "KamedaR_DATA_2021-08-07_1709.csv",
      sep="")) %>% 
  mutate(institute=0)
survey.Kameda.raw1<-
  read.csv(
    file=paste(
      data.loc(),
      "KamedaR_DATA_2021-08-07_1713.csv",
      sep="")) %>% 
  mutate(institute=1)
survey.Kameda.raw<-
  rbind(
    survey.Kameda.raw0,
    survey.Kameda.raw1)
rm(survey.Kameda.raw1,survey.Kameda.raw0)

survey.Kameda<-
  survey.Kameda.raw %>% 
  transmute(
    experience=
      factor(
        experience-1,
        levels=c(0:3),
        labels=c("Unrecognized","Inexperienced","Novice","Skilled")),
    attendance=
      factor(
        lesson_attendance-1,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Mon=
      factor(
        preffered_weekday___1,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Tue=
      factor(
        preffered_weekday___2,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Wed=
      factor(
        preffered_weekday___3,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Thu=
      factor(
        preffered_weekday___4,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Fri=
      factor(
        preffered_weekday___5,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Sat=
      factor(
        preffered_weekday___6,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Sun=
      factor(
        preffered_weekday___7,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Morning=
      factor(
        preffered_time___1,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Noon=
      factor(
        preffered_time___2,
        levels=c(0,1),
        labels=c("No","Yes")),
    preff.Evening=
      factor(
        preffered_time___3,
        levels=c(0,1),
        labels=c("No","Yes")),
    basic.Install=
      factor(
        basic_items___1,
        levels=c(0,1),
        labels=c("No","Yes")),
    basic.DataWrangling=
      factor(
        basic_items___2,
        levels=c(0,1),
        labels=c("No","Yes")),
    basic.TableFigure=
      factor(
        basic_items___3,
        levels=c(0,1),
        labels=c("No","Yes")),
    basic.UnivalAnalysis=
      factor(
        basic_items___4,
        levels=c(0,1),
        labels=c("No","Yes")),
    basic.MultivalAnalysis=
      factor(
        basic_items___5,
        levels=c(0,1),
        labels=c("No","Yes")),
    advance.OutlierMissing=
      factor(
        advanced_items___1,
        levels=c(0,1),
        labels=c("No","Yes")),
    advance.Survival=
      factor(
        advanced_items___2,
        levels=c(0,1),
        labels=c("No","Yes")),
    advance.Matching=
      factor(
        advanced_items___3,
        levels=c(0,1),
        labels=c("No","Yes")),
    advance.Prediction=
      factor(
        advanced_items___4,
        levels=c(0,1),
        labels=c("No","Yes")),
    advance.MachineLearning=
      factor(
        advanced_items___5,
        levels=c(0,1),
        labels=c("No","Yes")),
    advance.Writing=
      factor(
        advanced_items___6,
        levels=c(0,1),
        labels=c("No","Yes")),
    Institute=
      factor(
        institute,
        levels=c(0,1),
        labels=c("Kameda","Other")))

library(tableone)
knitr::kable(
  print(
    tableone::CreateTableOne(
      data=survey.Kameda,
      strata = "Institute",
      test = F,
      includeNA = T,
      addOverall = T)))


